### ISSUE TITLE
Define UI/UX Documentation

### ISSUE THREAD

**Issue by jvribeiros** [vpz-jvt/python-configurator#1]
# UI/UX

## UX
Define the app pipeline for the user to configure a new dynamic table.

- [x] 

![Image](https://user-images.githubusercontent.com/24698286/183745393-8ec91363-79d1-4960-b619-7c3800f2718c.jpeg)

Available on: https://lucid.app/lucidchart/c340cf92-7f98-4a80-8fd3-3eff21fcf065/edit?viewport_loc=-744%2C-92%2C3328%2C1478%2C0_0&invitationId=inv_a8cfa8e3-02b0-41ed-a1fe-3c1bd5cc7012#

## UI

Define the screens prototypes.

- [ ] 

Screen 1:
![Image](https://user-images.githubusercontent.com/24698286/183756687-866d1cd7-f248-47ff-b35e-f21ec77df966.png)

Screen 2:

![Image](https://user-images.githubusercontent.com/24698286/183757562-23f431a4-58f4-42d4-b847-ee10364c7a4f.png)

**Comment by vitorpohlenz** [comment]
The two screens are greate! I think it is exaclty what we need for the first version.

Just two doubts.
Whats is the difference between "Insert Custom Column" and "Create New Column" ?
How can we make it clear that is the first row that will be used to "Fill Rows" ?

**Comment by jvribeiros** [comment]
![Image](https://user-images.githubusercontent.com/24698286/184130004-43c4499f-6a46-4e9b-95eb-fe6e507267d1.png)
